-- SELECT * FROM shoapp.products;
-- Where Filtreleme Operatörleri 
-- select * from shoapp.products where Price Between 5000 and 8000
-- select * from shoapp.products where ıd Between 1 and 4 --> 1 ve 4 arasındaki sayıları filtreler
-- select * from shoapp.products where ıd Not Between 1 and 4 
-- select * from shoapp.products where Category='Bilgisayar'
-- select * from shoapp.products where Category IN ('Telefon','Bilgisayar') --> Telefon ve Bilgisayar kategorisini ayrı ayrı tanımlamadan bize filtreler
-- select * from shoapp.products where Category NOT IN ('Bilgisayar')
-- select * from shoapp.products where Name LIKE '%Iphone%'  --> İçinde kelime aramak istersek kullnılır
-- select * from shoapp.products where Name LIKE 'I%' --> Başı I harfiyle başlayan sonu önemli değil
-- select * from shoapp.products where Name LIKE '_e%' -->İkinci Kareketeri E olanı filtreler
-- select * from shoapp.products where Not Name LIKE '%Iphone%'
-- select * from shoapp.products where Name LIKE '%Iphone%' and Price >= 7000
-- select * from shoapp.products where Name LIKE '%Iphone%' and Description LIKE '%çift sim kart%' 

-- Kayıt Sıralama
-- select * from shoapp.products order by Price --> Fiyata göre sıraladım
-- select * from shoapp.products order by Name ASC --> Artan düzene göre sıralar
-- select * from shoapp.products order by Name DESC --> Azalan düzene göre sıralar
-- select * from shoapp.products order by Category,Price 
-- select * from shoapp.products order by Category DESC,Price ASC