-- SELECT * FROM shoapp.products;
-- SELECT * FROM shoapp.products;
-- SQL Fonksiyonaları
-- SELECT min(Price) from shoapp.products ,
-- SELECT min(Price)as 'minimumfiyat' from shoapp.products  
-- SELECT max(Price)as 'maksimumfiyat' from shoapp.products  
-- SELECT name from shoapp.products order by price
-- SELECT name,price from shoapp.products 
-- SELECT name,price from shoapp.products order by price limit 2
-- SELECT count(*) FROM shoapp.products --> satırı sayar
-- SELECT count(ıd) as adet FROM shoapp.products
-- SELECT avg(Price) as ortalamafiyat FROM shoapp.products
-- SELECT sum(Price) as Toplam FROM shoapp.products
-- SELECT sum(Price * Stock) as ToplamGelir FROM shoapp.products