-- SELECT * FROM shoapp.products;
-- select * from shoapp.products
-- select Name from shoapp.products
-- select Name,Price from shoapp.products
-- select Name as ProductName from shoapp.products
-- select Name as ProductName, Price as Fiyat from shoapp.products
-- select * from shoapp.products where Name = 'Iphone 8'
-- select * from shoapp.products where Price > 5000
-- select * from shoapp.products where Price >= 5000 and Price <= 7000
-- select * from shoapp.products where Name = 'Iphone 9' and (Price = 6000 or Price = 6500)

