-- SELECT * FROM shoapp.products;
-- SELECT length('İsmail') FROM shoapp.products
-- SELECT name , length(name) as karakteruzunluğu FROM shoapp.products
-- SELECT name , left(name , 3) as ilk3karakter FROM shoapp.products
-- SELECT name ,concat( left(name , 3), '...') as ilk3karakter FROM shoapp.products --> concat istediğimiz parametreyi birleştirir.
-- SELECT name ,concat('...', right(Description,4)) as son3karakter FROM shoapp.products
-- SELECT name , lower(name) as küçükharf FROM shoapp.products
-- SELECT name , upper(name) as büyükkharf FROM shoapp.products
-- SELECT name , replace(name, ' ','-') as değiştirilen FROM shoapp.products
-- SELECT name , lower(replace(name, ' ','-'))as değiştirilen FROM shoapp.products
-- SELECT name , trim(name) as boşluğualınan FROM shoapp.products
-- SELECT name , ltrim(name) as boşluğualınan FROM shoapp.products
-- SELECT name , rtrim(name) as boşluğualınan FROM shoapp.products
